services:
  - type: web
    name: gab-echo-laravel
    env: php
    region: oregon
    branch: main
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    autoDeploy: true
